import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='navbar bg-base-100'>
          <div className='navbar-start'>
            <a className='btn btn-ghost text-xl text-primary'>LOGO</a>
          </div>
          <div className="navbar-center">
            <div className='form-control'>
              <input
                type='text'
                placeholder='Tìm kiếm'
                className='w-20 input input-sm rounded-none	input-bordered border-primary text-primary sm:w-60 md:w-80'
              />
            </div>
          </div>
          <div className='navbar-end gap-1'>
            <button className='btn btn-sm btn-outline normal-case'>
              Đăng ký
            </button>
            <button className='btn btn-sm btn-primary normal-case	text-white'>
              Đăng nhập
            </button>
          </div>
        </div>
        <div className='navbar bg-secondary'>
          <div className='flex-1 gap-1'>
            <div className="btn btn-sm btn-ghost">Trang chủ</div>
            <div className="btn btn-sm btn-ghost">Thời sự</div>
            <div className="btn btn-sm btn-ghost">Thế giới</div>
            <div className="btn btn-sm btn-ghost">Kinh tế</div>
            <div className="btn btn-sm btn-ghost">Thể thao</div>
          </div>
          <div className='dropdown dropdown-end'>
            <div
              tabIndex={0}
              role='button'
              className='btn m-1 btn-sm btn-primary normal-case text-white lg:hidden'
            >
              Tất cả chuyên mục
            </div>
            <ul className='dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52'>
              <li>
                <a>Item 1</a>
              </li>
              <li>
                <a>Item 2</a>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
